# Generated by Django 2.1.dev20180416173837 on 2018-04-17 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4000)),
                ('company_code_01', models.CharField(max_length=40)),
                ('company_code_02', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4000)),
                ('company_code_01', models.CharField(max_length=40)),
                ('company_code_02', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code_01', models.CharField(max_length=40)),
                ('company_code_02', models.CharField(max_length=40)),
                ('company_code_03', models.CharField(max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_evaluator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.CharField(max_length=4000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('document_code_01', models.CharField(max_length=255)),
                ('document_code_02', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=4000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=4000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Version'),
        ),
        migrations.AddField(
            model_name='employee',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Year'),
        ),
        migrations.AddField(
            model_name='designation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Version'),
        ),
        migrations.AddField(
            model_name='designation',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Year'),
        ),
        migrations.AddField(
            model_name='department',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Version'),
        ),
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_data.Year'),
        ),
    ]
